import { CompleteEventType } from '@/types/hiStory';
import { EventDetailType } from '@/pages/hi-story/completed-events/[eventId]';

export const mockCompletedEventList: CompleteEventType[] = [
  {
    eventId: 1,
    title: '완료된 첫 번째 이벤트',
    category: '일상',
    eventStatus: 'termination',
    startDate: '2023-09-01',
    endDate: '2023-09-01',
    fileUrl: 'https://example.com/event1.jpg',
    emotion: 'JOY',
    totalQuestionCount: 5,
    totalAnswerCount: 5,
    representativeQuestion: {
      questionId: 201,
      content: '이벤트를 통해 무엇을 배웠나요?',
      isPriority: false,
      isAnswer: true,
      myAnswer: '새로운 경험의 중요성을 깨달았습니다.',
      questionDate: '2023-09-01',
      answeredAt: '2023-09-01',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '완료된 첫 번째 이벤트',
    },
  },
  {
    eventId: 2,
    title: '완료된 두 번째 이벤트',
    category: '여행',
    eventStatus: 'termination',
    startDate: '2023-09-02',
    endDate: '2023-09-03',
    fileUrl: 'https://example.com/event2.jpg',
    emotion: 'HAPPINESS',
    totalQuestionCount: 7,
    totalAnswerCount: 6,
    representativeQuestion: {
      questionId: 202,
      content: '가장 인상 깊었던 순간은?',
      isPriority: true,
      isAnswer: true,
      myAnswer: '석양을 바라보며 느낀 평화로움이었습니다.',
      questionDate: '2023-09-03',
      answeredAt: '2023-09-03',
      fileUrl: 'https://example.com/sunset.jpg',
      type: 'IMAGE',
      eventTitle: '완료된 두 번째 이벤트',
    },
  },
  {
    eventId: 3,
    title: '완료된 세 번째 이벤트',
    category: '학습',
    eventStatus: 'termination',
    startDate: '2023-09-04',
    endDate: '2023-09-04',
    fileUrl: 'https://example.com/event3.jpg',
    emotion: 'SATISFACTION',
    totalQuestionCount: 4,
    totalAnswerCount: 4,
    representativeQuestion: {
      questionId: 203,
      content: '새롭게 알게 된 사실이 있나요?',
      isPriority: false,
      isAnswer: true,
      myAnswer: '내가 어케 알아~',
      questionDate: '2023-09-04',
      answeredAt: '2023-09-04',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '완료된 세 번째 이벤트',
    },
  },
  {
    eventId: 4,
    title: '예술적인소프트웨어 대회',
    category: '취미',
    eventStatus: 'termination',
    startDate: '2023-10-01',
    endDate: '2023-10-31',
    fileUrl: 'https://example.com/event4.jpg',
    emotion: 'EXPECTATION',
    totalQuestionCount: 10,
    totalAnswerCount: 8,
    representativeQuestion: {
      questionId: 204,
      content: '이번 달 가장 인상 깊었던 책은?',
      isPriority: false,
      isAnswer: true,
      myAnswer: '『사피엔스』, 인류 역사에 대한 새로운 시각을 얻었습니다.',
      questionDate: '2023-10-31',
      answeredAt: '2023-10-31',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '예술적인소프트웨어 대회',
    },
  },
  {
    eventId: 5,
    title: '30일 건강 챌린지',
    category: '건강',
    eventStatus: 'termination',
    startDate: '2023-11-01',
    endDate: '2023-11-30',
    fileUrl: 'https://example.com/event5.jpg',
    emotion: 'HOPE',
    totalQuestionCount: 30,
    totalAnswerCount: 28,
    representativeQuestion: {
      questionId: 205,
      content: '한 달간의 변화 중 가장 큰 것은?',
      isPriority: false,
      isAnswer: true,
      myAnswer:
        '아침 기상 시간이 규칙적으로 변했고, 전반적인 컨디션이 좋아졌습니다.',
      questionDate: '2023-11-30',
      answeredAt: '2023-11-30',
      fileUrl: 'https://example.com/health-chart.jpg',
      type: 'IMAGE',
      eventTitle: '30일 건강 챌린지',
    },
  },
  {
    eventId: 6,
    title: '연말 자선 봉사활동',
    category: '사회',
    eventStatus: 'termination',
    startDate: '2023-12-20',
    endDate: '2023-12-24',
    fileUrl: 'https://example.com/event6.jpg',
    emotion: 'LOVE',
    totalQuestionCount: 6,
    totalAnswerCount: 6,
    representativeQuestion: {
      questionId: 206,
      content: '봉사활동을 통해 느낀 점은?',
      isPriority: false,
      isAnswer: true,
      myAnswer:
        '작은 도움이 모여 큰 변화를 만들 수 있다는 것을 직접 경험했습니다.',
      questionDate: '2023-12-24',
      answeredAt: '2023-12-24',
      fileUrl: 'https://example.com/volunteer-audio.mp3',
      type: 'VOICE',
      eventTitle: '연말 자선 봉사활동',
    },
  },
];

export const mockEventDetailList: EventDetailType[] = [
  {
    eventId: 1,
    title: '완료된 첫 번째 이벤트',
    emotion: '행복',
    eventStatus: 'termination',
    startDate: '2023-09-01',
    endDate: '2023-09-01',
    memo: '일상의 소중함을 깨달은 하루',
    fileUrl: 'https://example.com/event1.jpg',
    totalQuestionCount: 3,
    totalAnswerCount: 3,
    occurrenceTime: '09:00',
    representativeQuestion: {
      questionId: 201,
      content: '이벤트를 통해 무엇을 배웠나요?',
      isAnswer: true,
      myAnswer: '새로운 경험의 중요성을 깨달았습니다.',
      answeredAt: '2023-09-01',
      isPriority: true,
      questionDate: '2023-09-01',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '완료된 첫 번째 이벤트',
    },
    questionContent: [
      {
        questionId: 201,
        content: '이벤트를 통해 무엇을 배웠나요?',
        isAnswer: true,
        myAnswer: '새로운 경험의 중요성을 깨달았습니다.',
        answeredAt: '2023-09-01',
        isPriority: true,
        questionDate: '2023-09-01',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '완료된 첫 번째 이벤트',
      },
      {
        questionId: 202,
        content: '오늘 하루 중 가장 기억에 남는 순간은?',
        isAnswer: true,
        myAnswer: '가족과 함께한 저녁 식사 시간이었습니다.',
        answeredAt: '2023-09-01',
        isPriority: false,
        questionDate: '2023-09-01',
        fileUrl: 'https://example.com/family-dinner.jpg',
        type: 'IMAGE',
        eventTitle: '완료된 첫 번째 이벤트',
      },
    ],
  },
  {
    eventId: 2,
    title: '완료된 두 번째 이벤트',
    emotion: '설렘',
    eventStatus: 'termination',
    startDate: '2023-09-02',
    endDate: '2023-09-03',
    memo: '잊지 못할 주말 여행',
    fileUrl: 'https://example.com/event2.jpg',
    totalQuestionCount: 2,
    totalAnswerCount: 2,
    occurrenceTime: '10:30',
    representativeQuestion: {
      questionId: 203,
      content: '가장 인상 깊었던 순간은?',
      isAnswer: true,
      myAnswer: '석양을 바라보며 느낀 평화로움이었습니다.',
      answeredAt: '2023-09-02',
      isPriority: true,
      questionDate: '2023-09-02',
      fileUrl: 'https://example.com/sunset.jpg',
      type: 'IMAGE',
      eventTitle: '완료된 두 번째 이벤트',
    },
    questionContent: [
      {
        questionId: 203,
        content: '가장 인상 깊었던 순간은?',
        isAnswer: true,
        myAnswer: '석양을 바라보며 느낀 평화로움이었습니다.',
        answeredAt: '2023-09-02',
        isPriority: true,
        questionDate: '2023-09-02',
        fileUrl: 'https://example.com/sunset.jpg',
        type: 'IMAGE',
        eventTitle: '완료된 두 번째 이벤트',
      },
      {
        questionId: 204,
        content: '이번 여행에서 새롭게 시도해본 것이 있다면?',
        isAnswer: true,
        myAnswer: '현지 요리 수업에 참여해 전통 음식을 만들어 보았습니다.',
        answeredAt: '2023-09-03',
        isPriority: false,
        questionDate: '2023-09-03',
        fileUrl: 'https://example.com/cooking-class.mp3',
        type: 'VOICE',
        eventTitle: '완료된 두 번째 이벤트',
      },
    ],
  },
  {
    eventId: 3,
    title: '완료된 세 번째 이벤트',
    emotion: '호기심',
    eventStatus: 'termination',
    startDate: '2023-09-04',
    endDate: '2023-09-04',
    memo: '새로운 지식의 발견',
    fileUrl: 'https://example.com/event3.jpg',
    totalQuestionCount: 1,
    totalAnswerCount: 1,
    occurrenceTime: '14:00',
    representativeQuestion: {
      questionId: 205,
      content: '새롭게 알게 된 사실이 있나요?',
      isAnswer: true,
      myAnswer: '인공지능의 윤리적 측면에 대해 깊이 있게 배웠습니다.',
      answeredAt: '2023-09-04',
      isPriority: true,
      questionDate: '2023-09-04',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '완료된 세 번째 이벤트',
    },
    questionContent: [
      {
        questionId: 205,
        content: '새롭게 알게 된 사실이 있나요?',
        isAnswer: true,
        myAnswer: '인공지능의 윤리적 측면에 대해 깊이 있게 배웠습니다.',
        answeredAt: '2023-09-04',
        isPriority: true,
        questionDate: '2023-09-04',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '완료된 세 번째 이벤트',
      },
    ],
  },
];
